[project]
name = "project"
version = "0.0.1"
standard = "C++11"

[build]
tool = "CMake"
version = "3.15"

[lint]
tool = "clang-tidy"

[format]
tool = "clang-format"

[dependencies]
librdkafka = { git="https://github.com/confluentinc/librdkafka", version="2.2.0" }

